export const TASK_TRACKER_TITLE = "Task Tracker";
export const CALCULATE_TITLE = "Calculator";
export const VIDEO_GALLERY = "Video Gallery";
export const SHOPPING_CART = "Shopping Cart";
export const TITLE = "EMI Calculator";
export const CALCULATOR_VALUE = "Monthly EMI : Rs.";
export const CALCULATOR_LOAN_AMOUNT = "Enter Loan Amount (INR):";
export const CALCULATOR_MONTHLY_INTEREST_RATE = "Enter Monthly Interest Rate(%):";
export const CALCULATOR_TENURE = "Enter Tenure(years):";
export const CLEAR_TEXT = "Clear";
export const SUBMIT_TEXT = "Submit";
export const WARNING_TEXT = "Negative value not allowed !!"